language: python
sudo: false
dist: trusty
cache: pip

env:
  global:
    - PYTHONFAULTHANDLER=x
    - SKIP_LATEX_BUILD=1
    - IS_PYTHON=true

matrix:
  include:
    - python: '3.6'
      env: TOXENV=mypy
    - python: '3.6'
      env: TOXENV=flake8

install:
  - if [ $IS_PYTHON = true ]; then pip install -U tox codecov; fi
  - if [ $IS_PYTHON = false ]; then npm install; fi

script:
  - if [ $IS_PYTHON = true ]; then tox -- -v; fi
  - if [ $IS_PYTHON = false ]; then npm test; fi

after_success:
  - if [[ -e .coverage ]]; then codecov -e $TOXENV; fi
